spring:
  # DataSource Configuration
  datasource:
    url: jdbc:mysql://34.41.128.5:3306/<course_sniper>
    username: CRUDuser
    password: 8#/Y$Cm;r/28KRV~
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  
 