runtime: java17
instance_class: F2  

#leverage app enginer auto scaling
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  min_idle_instances: automatic  
  max_idle_instances: automatic  
  max_concurrent_requests: 10

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

# Handlers (URL routing)
handlers:
- url: /.*
  script: auto
  secure: always  # All requests over HTTPS
  redirect_http_response_code: 301




service: default  

