spring:
  # DataSource Configuration
  datasource:
    url: NULL
    username: NULL
    password: NULL
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect